name: 2 Generic Boosting Trainer
description: Trains boosting algorithms based on configuration with algorithm-specific metrics
inputs:
  - name: data_path
    type: Dataset
    description: Preprocessed data from preprocessor
  - name: preprocessing_pipeline
    type: Model
    description: Preprocessing pipeline from preprocessor
  - name: config
    type: String
    description: Algorithm configuration as JSON string
outputs:
  - name: trained_model
    type: Model
    description: Trained boosting model
  - name: training_history
    type: String
    description: Training metrics and history
  - name: model_coefficients
    type: String
    description: Feature importances and coefficients

implementation:
  container:
    image: nikhilv215/nesy-factory:v22
    command:
      - sh
      - -c
      - |
        set -e
        echo "Installing required packages..."
        python3 -m pip install --quiet --no-warn-script-location pandas numpy scikit-learn xgboost catboost lightgbm
        echo "Packages installed successfully"
        
        python3 -u -c "
        import sys, os, pickle, json, pandas as pd, numpy as np
        from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
        from sklearn.ensemble import GradientBoostingRegressor, AdaBoostRegressor
        from xgboost import XGBRegressor
        from catboost import CatBoostRegressor
        from lightgbm import LGBMRegressor
        import argparse

        print('STARTING BOOSTING TRAINER')

        class DataWrapper:
            def __init__(self, data_dict=None):
                if data_dict:
                    self.__dict__.update(data_dict)

        parser = argparse.ArgumentParser()
        parser.add_argument('--data_path', type=str, required=True)
        parser.add_argument('--preprocessing_pipeline', type=str, required=True)
        parser.add_argument('--config', type=str, required=True)
        parser.add_argument('--trained_model', type=str, required=True)
        parser.add_argument('--training_history', type=str, required=True)
        parser.add_argument('--model_coefficients', type=str, required=True)
        args = parser.parse_args()

        print('Arguments loaded')

        # Check if input paths exist
        if not os.path.exists(args.data_path):
            print('ERROR: data_path does not exist!')
            sys.exit(1)
        if not os.path.exists(args.preprocessing_pipeline):
            print('ERROR: preprocessing_pipeline path does not exist!')
            sys.exit(1)

        # Load data
        try:
            with open(args.data_path, 'rb') as f:
                data_wrapper = pickle.load(f)
            print('Data loaded successfully')
        except Exception as e:
            print('ERROR loading data: ' + str(e))
            sys.exit(1)

        # Load preprocessor
        try:
            with open(args.preprocessing_pipeline, 'rb') as f:
                preprocessor = pickle.load(f)
            print('Preprocessing pipeline loaded successfully')
        except Exception as e:
            print('ERROR loading preprocessor: ' + str(e))
            sys.exit(1)

        # Load config
        try:
            config = json.loads(args.config)
            algorithm = config.get('algorithm', 'GradientBoosting')
            parameters = config.get('parameters', {})
            print(f'Config loaded: algorithm={algorithm}')
        except Exception as e:
            print('ERROR loading config: ' + str(e))
            sys.exit(1)

        # Extract data from wrapper
        X_train = data_wrapper.X_train
        y_train = data_wrapper.y_train
        X_test = data_wrapper.X_test
        y_test = data_wrapper.y_test
        dataset_info = getattr(data_wrapper, 'dataset_info', {})

        print(f'Training {algorithm} on {X_train.shape[0]} samples')
        print(f'Dataset: {dataset_info.get(\"dataset_name\", \"Unknown\")}')

        # Algorithm mapping
        algorithm_map = {
            'GradientBoosting': GradientBoostingRegressor,
            'AdaBoost': AdaBoostRegressor,
            'XGBoost': XGBRegressor,
            'CatBoost': CatBoostRegressor,
            'LightGBM': LGBMRegressor
        }

        if algorithm not in algorithm_map:
            raise ValueError(f'Algorithm {algorithm} not supported. Available: {list(algorithm_map.keys())}')

        model_class = algorithm_map[algorithm]

        # Set default parameters if not provided
        default_params = {
            'GradientBoosting': {'n_estimators': 100, 'learning_rate': 0.1, 'max_depth': 3, 'random_state': 42},
            'AdaBoost': {'n_estimators': 50, 'learning_rate': 1.0, 'random_state': 42},
            'XGBoost': {'n_estimators': 100, 'learning_rate': 0.1, 'max_depth': 6, 'random_state': 42},
            'CatBoost': {'iterations': 100, 'learning_rate': 0.1, 'depth': 6, 'random_state': 42, 'verbose': False},
            'LightGBM': {'n_estimators': 100, 'learning_rate': 0.1, 'max_depth': -1, 'random_state': 42}
        }

        final_params = {**default_params.get(algorithm, {}), **parameters}
        print(f'Using parameters: {final_params}')

        # Train model
        try:
            model = model_class(**final_params)
            model.fit(X_train, y_train)
            print('Model training completed successfully')
        except Exception as e:
            print('ERROR during model training: ' + str(e))
            sys.exit(1)

        # Predictions
        y_pred_train = model.predict(X_train)
        y_pred_test = model.predict(X_test)

        # Calculate metrics
        train_r2 = r2_score(y_train, y_pred_train)
        test_r2 = r2_score(y_test, y_pred_test)
        train_mae = mean_absolute_error(y_train, y_pred_train)
        test_mae = mean_absolute_error(y_test, y_pred_test)
        train_rmse = np.sqrt(mean_squared_error(y_train, y_pred_train))
        test_rmse = np.sqrt(mean_squared_error(y_test, y_pred_test))

        # Feature importances
        feature_names = list(X_train.columns) if hasattr(X_train, 'columns') else [f'feature_{i}' for i in range(X_train.shape[1])]
        if hasattr(model, 'feature_importances_'):
            importances = model.feature_importances_
            coefficients_data = []
            for name, importance in zip(feature_names, importances):
                coefficients_data.append({
                    'feature': name,
                    'importance': float(importance),
                    'importance_percent': float(importance * 100)
                })
        else:
            coefficients_data = [{'feature': name, 'importance': 0, 'importance_percent': 0} for name in feature_names]

        # Training history
        history = {
            'algorithm': algorithm,
            'parameters': final_params,
            'train_metrics': {
                'r2_score': float(train_r2),
                'mae': float(train_mae),
                'rmse': float(train_rmse)
            },
            'test_metrics': {
                'r2_score': float(test_r2),
                'mae': float(test_mae),
                'rmse': float(test_rmse)
            },
            'feature_importances': coefficients_data,
            'training_samples': len(X_train),
            'test_samples': len(X_test),
            'dataset_name': dataset_info.get('dataset_name', 'Unknown')
        }

        # Save outputs
        try:
            os.makedirs(os.path.dirname(args.trained_model), exist_ok=True)
            os.makedirs(os.path.dirname(args.training_history), exist_ok=True)
            os.makedirs(os.path.dirname(args.model_coefficients), exist_ok=True)
            
            with open(args.trained_model, 'wb') as f:
                pickle.dump(model, f)
            
            with open(args.training_history, 'w') as f:
                json.dump(history, f, indent=2)
            
            coefficients_df = pd.DataFrame(coefficients_data)
            coefficients_csv = coefficients_df.to_csv(index=False)
            with open(args.model_coefficients, 'w') as f:
                f.write(coefficients_csv)
            
            print('Training completed successfully')
            print(f'Test R²: {test_r2:.4f}')
            print(f'Test RMSE: {test_rmse:.4f}')
        except Exception as e:
            print('ERROR saving results: ' + str(e))
            sys.exit(1)
        "
    args:
      - --data_path
      - {inputPath: data_path}
      - --preprocessing_pipeline
      - {inputPath: preprocessing_pipeline}
      - --config
      - {inputValue: config}
      - --trained_model
      - {outputPath: trained_model}
      - --training_history
      - {outputPath: training_history}
      - --model_coefficients
      - {outputPath: model_coefficients}
