name: 2 Unified Boosting Trainer
description: Trains boosting model using unified configuration with enhanced schema outputs
inputs:
  - name: processed_data
    type: Dataset
    description: Preprocessed data from preprocessor
  - name: model_in
    type: Model
    description: Model from model builder
  - name: config_str
    type: String
    description: 'Unified configuration JSON string'
outputs:
  - name: trained_model
    type: Model
  - name: training_history
    type: String
  - name: model_coefficients
    type: String
  - name: epoch_loss
    type: String

implementation:
  container:
    image: nikhilv215/nesy-factory:v22
    command:
      - sh
      - -c
      - |
        python3 -m pip install --quiet xgboost catboost lightgbm
        exec "$0" "$@"
      - python3
      - -u
      - -c
      - |
        import sys, os, pickle, json, pandas as pd, numpy as np
        from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, log_loss
        from sklearn.ensemble import GradientBoostingRegressor, AdaBoostRegressor, GradientBoostingClassifier, AdaBoostClassifier
        import argparse

        # Define DataWrapper class FIRST before unpickling
        class DataWrapper:
            def __init__(self, data_dict):
                self.__dict__.update(data_dict)

        # Define BoostingModel class for unpickling from Model Builder
        class BoostingModel:
            def __init__(self, algorithm, task, parameters):
                self.algorithm = algorithm
                self.task = task
                self.parameters = parameters
                self.is_fitted = False
                self.model_type = f"{algorithm} for {task}"

        print("STARTING UNIFIED BOOSTING TRAINER")

        # Import optional packages
        try:
            from xgboost import XGBRegressor, XGBClassifier
            print("XGBoost available")
        except ImportError:
            XGBRegressor, XGBClassifier = None, None
            print("XGBoost not available")
        try:
            from catboost import CatBoostRegressor, CatBoostClassifier
            print("CatBoost available")
        except ImportError:
            CatBoostRegressor, CatBoostClassifier = None, None
            print("CatBoost not available")
        try:
            from lightgbm import LGBMRegressor, LGBMClassifier
            print("LightGBM available")
        except ImportError:
            LGBMRegressor, LGBMClassifier = None, None
            print("LightGBM not available")

        parser = argparse.ArgumentParser()
        parser.add_argument('--processed_data', type=str, required=True)
        parser.add_argument('--model_in', type=str, required=True)
        parser.add_argument('--config_str', type=str, required=True)
        parser.add_argument('--trained_model', type=str, required=True)
        parser.add_argument('--training_history', type=str, required=True)
        parser.add_argument('--model_coefficients', type=str, required=True)
        parser.add_argument('--epoch_loss', type=str, required=True)
        args = parser.parse_args()

        # Load data, model, and config
        with open(args.processed_data, 'rb') as f:
            data_wrapper = pickle.load(f)
        
        config = json.loads(args.config_str)

        # Extract data and config
        X_train = data_wrapper.X_train
        y_train = data_wrapper.y_train
        X_test = data_wrapper.X_test
        y_test = data_wrapper.y_test
        feature_names = data_wrapper.feature_names
        dataset_info = getattr(data_wrapper, 'dataset_info', {})
        
        model_config = config.get('model', {})
        algorithm = model_config.get('algorithm', 'GradientBoosting')
        task = config.get('pipeline', {}).get('task', 'classification')
        parameters = model_config.get('parameters', {})

        print(f'Training {algorithm} for {task} on {X_train.shape[0]} samples')

        # Algorithm mapping
        algorithm_map = {
            'regression': {
                'GradientBoosting': GradientBoostingRegressor,
                'AdaBoost': AdaBoostRegressor,
                'XGBoost': XGBRegressor if XGBRegressor else None,
                'CatBoost': CatBoostRegressor if CatBoostRegressor else None,
                'LightGBM': LGBMRegressor if LGBMRegressor else None
            },
            'classification': {
                'GradientBoosting': GradientBoostingClassifier,
                'AdaBoost': AdaBoostClassifier,
                'XGBoost': XGBClassifier if XGBClassifier else None,
                'CatBoost': CatBoostClassifier if CatBoostClassifier else None,
                'LightGBM': LGBMClassifier if LGBMClassifier else None
            }
        }

        if algorithm not in algorithm_map[task] or algorithm_map[task][algorithm] is None:
            available = list(algorithm_map[task].keys())
            raise ValueError(f'Algorithm {algorithm} not available for {task}. Available: {available}')

        model_class = algorithm_map[task][algorithm]

        # Set default parameters
        default_params = {
            'GradientBoosting': {'n_estimators': 100, 'learning_rate': 0.1, 'max_depth': 3, 'random_state': 42},
            'AdaBoost': {'n_estimators': 50, 'learning_rate': 1.0, 'random_state': 42},
            'XGBoost': {'n_estimators': 100, 'learning_rate': 0.1, 'max_depth': 6, 'random_state': 42},
            'CatBoost': {'iterations': 100, 'learning_rate': 0.1, 'depth': 6, 'random_state': 42, 'verbose': False},
            'LightGBM': {'n_estimators': 100, 'learning_rate': 0.1, 'max_depth': -1, 'random_state': 42}
        }

        final_params = {**default_params.get(algorithm, {}), **parameters}
        
        # Enable training history collection for supported algorithms
        if algorithm in ['GradientBoosting', 'XGBoost', 'LightGBM']:
            if algorithm == 'GradientBoosting':
                final_params['subsample'] = 0.8  # For stochastic training curves
            elif algorithm == 'XGBoost':
                final_params['eval_metric'] = 'logloss' if task == 'classification' else 'rmse'
            elif algorithm == 'LightGBM':
                final_params['verbose'] = -1  # Disable logging

        print(f'Training with parameters: {final_params}')

        # Train model
        model = model_class(**final_params)
        
        # For algorithms that support staged prediction, collect training history
        epoch_data = []
        n_estimators = final_params.get('n_estimators', final_params.get('iterations', 100))
        
        if algorithm == 'GradientBoosting' and hasattr(model, 'staged_predict'):
            print("Collecting staged training history...")
            model.fit(X_train, y_train)
            
            # Collect training metrics at different stages
            for i, y_pred in enumerate(model.staged_predict(X_train)):
                if task == 'regression':
                    train_loss = mean_squared_error(y_train, y_pred)
                    val_pred = model.staged_predict(X_test)
                    val_loss = mean_squared_error(y_test, next(val_pred))
                else:
                    train_loss = log_loss(y_train, y_pred)
                    val_pred = model.staged_predict(X_test)
                    val_loss = log_loss(y_test, next(val_pred))
                
                epoch_data.append({
                    'epoch': i + 1,
                    'loss': float(train_loss),
                    'accuracy': float(accuracy_score(y_train, np.round(y_pred))) if task == 'classification' else float(r2_score(y_train, y_pred)),
                    'validation_loss': float(val_loss),
                    'validation_accuracy': float(accuracy_score(y_test, np.round(next(iter(model.staged_predict(X_test)))))) if task == 'classification' else float(r2_score(y_test, next(iter(model.staged_predict(X_test)))))
                })
                
                if i >= n_estimators - 1:
                    break
        else:
            # Standard training for other algorithms
            model.fit(X_train, y_train)
            print("Model training completed successfully")

        # Final predictions
        y_pred_train = model.predict(X_train)
        y_pred_test = model.predict(X_test)

        # Calculate metrics based on task
        if task == 'regression':
            train_metrics = {
                'r2_score': float(r2_score(y_train, y_pred_train)),
                'mae': float(mean_absolute_error(y_train, y_pred_train)),
                'rmse': float(np.sqrt(mean_squared_error(y_train, y_pred_train))),
                'mse': float(mean_squared_error(y_train, y_pred_train))
            }
            test_metrics = {
                'r2_score': float(r2_score(y_test, y_pred_test)),
                'mae': float(mean_absolute_error(y_test, y_pred_test)),
                'rmse': float(np.sqrt(mean_squared_error(y_test, y_pred_test))),
                'mse': float(mean_squared_error(y_test, y_pred_test))
            }
            # Calculate loss values for schema
            train_loss = train_metrics['mse']
            test_loss = test_metrics['mse']
            train_accuracy = train_metrics['r2_score']
            test_accuracy = test_metrics['r2_score']
        else:
            train_metrics = {
                'accuracy': float(accuracy_score(y_train, y_pred_train)),
                'precision': float(precision_score(y_train, y_pred_train, average='weighted', zero_division=0)),
                'recall': float(recall_score(y_train, y_pred_train, average='weighted', zero_division=0)),
                'f1_score': float(f1_score(y_train, y_pred_train, average='weighted', zero_division=0))
            }
            test_metrics = {
                'accuracy': float(accuracy_score(y_test, y_pred_test)),
                'precision': float(precision_score(y_test, y_pred_test, average='weighted', zero_division=0)),
                'recall': float(recall_score(y_test, y_pred_test, average='weighted', zero_division=0)),
                'f1_score': float(f1_score(y_test, y_pred_test, average='weighted', zero_division=0))
            }
            # Calculate loss values for schema
            train_loss = float(log_loss(y_train, model.predict_proba(X_train)))
            test_loss = float(log_loss(y_test, model.predict_proba(X_test)))
            train_accuracy = train_metrics['accuracy']
            test_accuracy = test_metrics['accuracy']
            
            if hasattr(model, 'predict_proba'):
                y_pred_proba_train = model.predict_proba(X_train)
                y_pred_proba_test = model.predict_proba(X_test)
                train_metrics['roc_auc'] = float(roc_auc_score(y_train, y_pred_proba_train, multi_class='ovr'))
                test_metrics['roc_auc'] = float(roc_auc_score(y_test, y_pred_proba_test, multi_class='ovr'))

        # If no epoch data was collected (for non-staged algorithms), create final epoch entry
        if not epoch_data:
            epoch_data = [{
                'epoch': n_estimators,
                'loss': train_loss,
                'accuracy': train_accuracy,
                'validation_loss': test_loss,
                'validation_accuracy': test_accuracy
            }]

        # Feature importances
        if hasattr(model, 'feature_importances_'):
            importances = model.feature_importances_
            coefficients_data = []
            for name, importance in zip(feature_names, importances):
                coefficients_data.append({
                    'feature': name,
                    'importance': float(importance),
                    'importance_percent': float(importance * 100)
                })
        else:
            coefficients_data = [{'feature': name, 'importance': 0, 'importance_percent': 0} for name in feature_names]

        # Enhanced training history for schema compatibility
        history = {
            'algorithm': algorithm,
            'task': task,
            'parameters': final_params,
            'train_metrics': train_metrics,
            'test_metrics': test_metrics,
            'feature_importances': coefficients_data,
            'training_samples': len(X_train),
            'test_samples': len(X_test),
            'dataset_name': dataset_info.get('dataset_name', 'Unknown'),
            'feature_names': feature_names,
            # Schema-compatible fields
            'epoch': n_estimators,
            'loss': train_loss,
            'accuracy': train_accuracy,
            'validation_loss': test_loss,
            'validation_accuracy': test_accuracy,
            'custom_metrics': test_metrics
        }

        # Save outputs
        os.makedirs(os.path.dirname(args.trained_model) or ".", exist_ok=True)
        os.makedirs(os.path.dirname(args.training_history) or ".", exist_ok=True)
        os.makedirs(os.path.dirname(args.model_coefficients) or ".", exist_ok=True)
        os.makedirs(os.path.dirname(args.epoch_loss) or ".", exist_ok=True)
        
        with open(args.trained_model, 'wb') as f:
            pickle.dump(model, f)
        with open(args.training_history, 'w') as f:
            json.dump(history, f, indent=2)
        with open(args.epoch_loss, 'w') as f:
            json.dump(epoch_data, f, indent=2)
        coefficients_df = pd.DataFrame(coefficients_data)
        with open(args.model_coefficients, 'w') as f:
            coefficients_df.to_csv(f, index=False)
        
        print(f"Training completed for {task}")
        print(f"Final epoch: {n_estimators}")
        print(f"Final training loss: {train_loss:.4f}, accuracy: {train_accuracy:.4f}")
        print(f"Final validation loss: {test_loss:.4f}, accuracy: {test_accuracy:.4f}")
    args:
      - --processed_data
      - {inputPath: processed_data}
      - --model_in
      - {inputPath: model_in}
      - --config_str
      - {inputValue: config_str}
      - --trained_model
      - {outputPath: trained_model}
      - --training_history
      - {outputPath: training_history}
      - --model_coefficients
      - {outputPath: model_coefficients}
      - --epoch_loss
      - {outputPath: epoch_loss}
